apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-demo2-deploy
  namespace: cicd-test
  labels:
    app: cicd-demo2
    env: cicd-test2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-demo2
        env: cicd-test2
    spec:
      containers:
      - name: demo2
        image: deploymentcoe.vodafone.skytapdns.com/cicd-demo2
        imagePullPolicy: Always
        ports:
         - containerPort: 9090
      imagePullSecrets:
      - name: demo-sec
      nodeSelector:
        namelabel: 2node
