apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cicd-demo2-ingress
  namespace: cicd-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.io
    http:
      paths:
      - backend:
          serviceName: cicd-demo2-svc
          servicePort: 7071
        path: /demo2/*