apiVersion: v1
kind: Service
metadata:
  name: cicd-demo2-svc
  namespace: cicd-test
spec:
  type: NodePort
  selector:
    app: cicd-demo2
  ports:
  - name: cicd-demo2-port
    port: 7072
    targetPort: 9090
  externalIPs:
    - 10.0.0.5
